name: siemens_test_task
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - matplotlib>=3.1
  - numpy>=1.19
  - pandas>=1.3
  - pysoundfile>=0.10
  - pytorch>=1.9
  - python-sounddevice>=0.4
  - scikit-learn>=0.23
  - scipy>=1.6
  - torchaudio>=0.9
  - torchvision>=0.2


